import { Inter, Roboto } from 'next/font/google'
import "./globals.css";

const roboto = Inter({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>{children}</body>
    </html>
  );
}
